import React from 'react'


// QUESTION 1: DOES THIS COMPONENT HAVE LOCAL STATE OR DOES IT GET IT FROM THE REDUX STORE?
// QUESTION 2: DOES THIS COMPONENT NEED TO BE ABLE TO DO SOMETHING AT A CERTAIN TIME?

function MyWall(props){
  return <p>Wall</p>
}

export default MyWall